name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: d3139574-536c-47ea-af32-599947af7384
          tenant-id: b506ae5f-374f-4e03-ad64-c1bc65e5ba82
          subscription-id: a2c7cbf4-a14a-489a-8121-f7c00be95199

      - name: 'Run az commands'
        run: |
          az account show
          az group list
