name: Connect to an AWS role from a GitHub repository
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
      id-token: write
      contents: read
jobs:
  check_arn:
    runs-on: ubuntu-latest
    steps:
      - name: Check ARN Format
        run: echo "${{ secrets.OIDC_ROLE_ARN }}" > out.txt && cat out.txt
